In [1]:
import pandas
import numpy

Arrays (lists)

In [3]:
ex_list = [1,2,3]

operations on list
- access
- search
- insert
- delete

In [4]:
# access - constant time 
result = ex_list[0]

In [5]:
# search - best case, use linear search for
# option 1: in, uses contains
if 1 in ex_list: print(True)
# option 2: for loop
for n in ex_list:
    if n == 1:
        print(True)
        break

True
True


In [6]:
# insert
# inserting at 0 (worst case, n runtime)

# insertaing at end OR appending (best case, 1 runtime)


python allocates new space using resize when more space needed at points: 0,4,8,16,25,35,46...

In [9]:
class Node:
    """
    An object for storing a single node in a linked list

    Attributes:
        data: Data stored in node
        next_node: Reference to next node in linked list
    """

    def __init__(self, data, next_node = None):
        self.data = data
        self.next_node = next_node

    def __repr__(self):
        return "<Node data: %s>" % self.data

class LinkedList:
    """
    Linear data structure that stores values in nodes. The list maintains a reference to the first node, also called head. Each node points to the next node in the list

    Attributes:
        head: The head node of the list
    """

    def __init__(self):
        self.head = None
        # Maintaining a count attribute allows for len() to be implemented in
        # constant time
        self.__count = 0

    def is_empty(self):
        """
        Determines if the linked list is empty
        Takes O(1) time
        """

        return self.head is None

    def __len__(self):
        """
        Returns the length of the linked list
        Takes O(1) time
        """

        return self.__count

    def add(self, data):
        """
        Adds new Node containing data to head of the list
        Also called prepend
        Takes O(1) time
        """

        new_head = Node(data, next_node=self.head)
        self.head = new_head
        self.__count += 1

    def search(self, key):
        """
        Search for the first node containing data that matches the key
        Returns the node or `None` if not found
        Takes O(n) time
        """

        current = self.head

        while current:
            if current.data == key:
                return current
            else:
                current = current.next_node
        return None

    def insert(self, data, index):
        """
        Inserts a new Node containing data at index position
        Insertion takes O(1) time but finding node at insertion point takes
        O(n) time.
        Takes overall O(n) time.
        """

        if index >= self.__count:
            raise IndexError('index out of range')

        # same as add
        if index == 0:
            self.add(data)
            return
        # create new node at index
        if index > 0:
            new = Node(data)
            position = index
            current = self.head

            # traverse till index reached
            while position > 1:
                current = current.next_node
                position -= 1

            prev_node = current
            next_node = current.next_node

            prev_node.next_node = new
            new.next_node = next_node

        self.__count += 1

    def node_at_index(self, index):
        """
        Returns the Node at specified index
        Takes O(n) time
        """

        if index >= self.__count:
            raise IndexError('index out of range')

        # return head if 0
        if index == 0:
            return self.head

        current = self.head
        position = 0

        # traverse till index
        while position < index:
            current = current.next_node
            position += 1

        return current

    def remove(self, key):
        """
        Removes Node containing data that matches the key
        Returns the node or `None` if key doesn't exist
        Takes O(n) time
        """

        current = self.head
        previous = None
        found = False

        # traverse until either found or current reaches node past tail (end of LL)
        while current and not found:
            if current.data == key and current is self.head:
                found = True
                self.head = current.next_node
                self.__count -= 1
                return current
            elif current.data == key:
                found = True
                previous.next_node = current.next_node
                self.__count -= 1
                return current
            else:
                previous = current
                current = current.next_node

        return None

    def remove_at_index(self, index):
        """
        Removes Node at specified index
        Takes O(n) time
        """

        if index >= self.__count:
            raise IndexError('index out of range')

        current = self.head

        if index == 0:
            self.head = current.next_node
            self.__count -= 1
            return current

        position = index

        while position > 1:
            current = current.next_node
            position -= 1

        prev_node = current
        current = current.next_node
        next_node = current.next_node

        prev_node.next_node = next_node
        self.__count -= 1

        return current


    def __iter__(self):
        current = self.head

        while current:
            yield current
            current = current.next_node


    def __repr__(self):
        """
        Return a string representation of the list.
        Takes O(n) time.
        """
        nodes = []
        current = self.head
        while current:
            if current is self.head:
                nodes.append("[Head: %s]" % current.data)
            elif current.next is None:
                nodes.append("[Tail: %s]" % current.data)
            else:
                nodes.append("[%s]" % current.data)
            current = current.next_node
        return  '-> '.join(nodes)

In [10]:
l = LinkedList()
l.add(1)
l.add(2)
l

[Head: 2]-> [Tail: 1]

# sets

### creating set

In [72]:
test_set_1 = {1,2,3,1, True} # duplicate 1 ignored, True also ignored (cast to 1)
print(test_set_1)
print(test_set_1)

test_set_2 = set((True,False)) # using constructor + tuple or list
test_set_3 = set(['1',1])
# test_set_3 = {'1',1}
print(test_set_2, test_set_3)
len(test_set_1)

{1, 2, 3}
{1, 2, 3}
{False, True} {'1', 1}


3

### accessing sets

In [20]:
# accessing sets: in
print(True in test_set_1) # True always 1, False always 0
print(1 not in test_set_1)

True
False


### adding to sets 

In [41]:
# add single elt to set: add
test_set_1.add(4)
print(test_set_1)

# combine sets: update
# can add any iterable (list, tuple, dictionaries)
test_set_a = {1,2}
test_set_b = {3,4}
test_set_a.update(test_set_b) # updates IN PLACE
test_set_a.update({5:6}) # adding dict appends keys
test_set_a

{1, 2, 3, 4}


{1, 2, 3, 4, 5}

### removing from sets

In [42]:
# removing
test_set_a.remove(5) # also inplace
# test_set_a.remove(5) # raises error if DNE
test_set_a.discard(5) # DOES NOT raise error if DNE
# .pop() removes random item\
# .clear() and del set to clear a set

### looping from sets

In [43]:
# loop as usual
for a in test_set_a:
    print(a)

1
2
3
4


### joining sets

In [58]:
# union (all values)
jset_1 = {1,2,3,4}
jset_2 = {3,4,5,6}
jset_1.union(jset_2) # returns new copy

{1, 2, 3, 4, 5, 6}

In [62]:
jset_3 = {6,7,8}
jset_1.union(jset_2,jset_3)
# jset_1 | jset_2 | jset_3 # same as union

{1, 2, 3, 4, 5, 6, 7, 8}

In [63]:
# intersection (common values)
jset_1.intersection(jset_2)

jset_1 & jset_2 # same thing

# jset_1.intersection_update(jset_2) # updates jset_1 in place
# jset_1

{3, 4}

In [64]:
# difference (those in FIRST SET, that aren't in SECOND)
jset_1.difference(jset_2)
jset_1 - jset_2 # same thing

{1, 2}

In [65]:
# sym difference (elts present in NEITHER SET)
jset_1.symmetric_difference(jset_2)

{1, 2, 5, 6}

### other useful methods

In [91]:
# copy a set
set_og = {1,2}
set_clone = set_og.copy()
# or set_clone = set(set_og)
set_clone.add(3)
print(set_clone, set_og)

{1, 2, 3} {1, 2}


In [69]:
# check if disjoint (has no intersection)
jset_1.isdisjoint(jset_2)
print(jset_1,jset_2)

{1, 2, 3, 4} {3, 4, 5, 6}


# dicts

### create dict

In [86]:
dict1 = {'a':1,'b':2,'c':3}
dict1

{'a': 1, 'b': 2, 'c': 3}

In [71]:
len(dict1)

2

### accessing dicts

In [95]:
# getting values
print(dict1['a'])
print(dict1.get('b')) # will not throw error if key DNE
print(dict1.get('d')) # instead None

1
1
None


In [96]:
# getting keys, values, items, looping through them
# for k in dict1: # same as below
for k in dict1.keys():
    print(k)
for k,v in dict1.items():
    print(k,v)
# can also use items to make a copy
dict1_copy = dict1.copy()
# or: dict1_copy = dict(dict1)
print(dict1_copy)
for v in dict1.values():
    print(v)

a
b
c
a 1
b 1
c 3
{'a': 1, 'b': 1, 'c': 3}
1
1
3


In [97]:
# check if key exists
if 'a' in dict1: print('a in dict1')

a in dict1


### modifying dict items

In [98]:
# updating dict items
dict1['a'] = 0
print(dict1)
# or update multiple
dict1.update({'a':1,'b':1})
print(dict1)
# use a nonexistent key to add items
dict1['d']=7
dict1

{'a': 0, 'b': 1, 'c': 3}
{'a': 1, 'b': 1, 'c': 3}


{'a': 1, 'b': 1, 'c': 3, 'd': 7}

In [99]:
# remove items
dict1.pop('d')
dict1

{'a': 1, 'b': 1, 'c': 3}

In [ ]:
# .popitem (removes last inserted item)
# del dict[key] same thing, del and clear() to completely clear

In [101]:
# nested dict... you know
# create a new dict with keys and default value
dict1a = dict1.fromkeys(('b','c'),3)
dict1a

{'b': 3, 'c': 3}

## matrices
When creating a matrix (an m x n list of lists) in Python, it is generally more efficient to predefine the matrix size rather than appending to the list of lists as you go. Predefining the matrix ensures that memory is allocated at once, and you avoid the overhead associated with repeatedly resizing lists.

In [2]:
m = 3  # Number of rows
n = 4  # Number of columns

# Create a matrix of size m x n filled with 0s
matrix = [[0 for _ in range(n)] for _ in range(m)]
matrix

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

## 1314. matrix block sum

In [ ]:
# 
class Solution:
    # soln 1: brute force
    # def matrixBlockSum(self, mat: List[List[int]], k: int) -> List[List[int]]:
    #     # return a matrix of block sums
    #     m = len(mat) # rows
    #     n = len(mat[0]) # columns
    #     # print('mat',mat, m,n)

    #     # initialize matrix
    #     answer = [[0 for _ in range(n)] for _ in range(m)]

    #     # calculate cells of block sum matrix
    #     for i in range(0,m):
    #         for j in range(0,n):
    #             # calculate block sum cell value, cumulatively
    #             block_sum = 0
    #             for r in range(max((i - k),0), min((i+k+1), m)):
    #                 for c in range(max((j - k),0), min((j+k+1),n)):
    #                     # print('r,c',r,c)
    #                     block_sum += mat[r][c] 
    #             answer[i][j] = block_sum
    #     return answer

    def matrixBlockSum(self, mat: List[List[int]], k: int) -> List[List[int]]:
        m, n = len(mat), len(mat[0])
        
        # Step 1: Compute the cumulative sum matrix
        cumulative_sum = [[0] * (n + 1) for _ in range(m + 1)]
        
        # populate 
        for i in range(1, m + 1):
            for j in range(1, n + 1):
                cumulative_sum[i][j] = mat[i-1][j-1] + cumulative_sum[i-1][j] + cumulative_sum[i][j-1] - cumulative_sum[i-1][j-1]
        
        # print('cumulative_sum',cumulative_sum)

        # Step 2: Use the cumulative sum matrix to compute the result
        result = [[0] * n for _ in range(m)]
        
        # iterate by row (through columns)
        for i in range(m):
            for j in range(n):


                r1 = max(0, i - k) # row lower bound (at least 0)
                c1 =  max(0, j - k) # col lower bound 
                r2 = min(m - 1, i + k) # row upper bound (at most og length)
                c2 = min(n - 1, j + k) # col upper boudn

                result[i][j] = (
                    cumulative_sum[r2 + 1][c2 + 1]
                    - cumulative_sum[r1][c2 + 1]
                    - cumulative_sum[r2 + 1][c1]
                    + cumulative_sum[r1][c1]
                )
                # print('result',result)
        
        return result


In [1]:
import numpy as np

In [9]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0][1]) # row 0, col 1
b=a.mean() # entire array
c=a.mean(axis = 0) # columns
d=a.mean(axis = 1) # rows
print(a,b,c,d)

2
[[1 2 3]
 [4 5 6]] 3.5 [2.5 3.5 4.5] [2. 5.]


In [12]:
z = np.array([[3,2,3],[1,0,6]])
# z.sort() # sorts by row
z[0].sort()
z

array([[2, 3, 3],
       [1, 0, 6]])

In [16]:
# subset, slice, index
print(a[1][2])
print(a[1,2])
print(a[0:1,1:]) # row 1, col 1:2

6
6
[[2 3]]


In [23]:
a[1,:] # a[1] same
print(a[::-1]) # reverses arrays elements (rows), not sub elements
np.array([a1[::-1] for a1 in a][::-1]) # reverse all elements

[[4 5 6]
 [1 2 3]]


array([[6, 5, 4],
       [3, 2, 1]])

In [26]:
np.ones([3,4])
np.zeros([1,5])

array([[0., 0., 0., 0., 0.]])